language: go

go:
- 1.8

before_install:
- go get github.com/onsi/ginkgo/ginkgo

install:
# Prevent default install task that does a `go get -t ./...`
- true

script:
- go build -v . 
- ./scripts/run-local-tests.sh


