dist: trusty
sudo: false

language: go

go:
- 1.8

before_install:
- go get github.com/onsi/ginkgo/ginkgo

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"must_not_be_empty",roles:["readWrite"]});'
  - sleep 10

services:
  - mongodb
  - elasticsearch

install:
# Prevent default install task that does a `go get -t ./...`
- true

script:
- go build -v .
- ./scripts/run-local-tests-travis.sh
